server:
  port: 8081
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: dynamic_route
            uri: http://localhost:8080
            predicates:
              - Path=/**
            filters:
              - RewritePath=/web/(?<remaining>.*), /${remaining} # Rewrite only /web requests