server:
  port: 8082
spring:
  cloud:
    gateway:
      routes:
        - id: dynamic_route
          uri: http://localhost:8080
          predicates:
            - Path=/web/**
logging:
  level:
    root: debug