server:
  port: 8082
spring:
  cloud:
    gateway:
      routes:
        - id: web_route
          uri: http://localhost:8080
          predicates:
            - Path=/web/**
springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: web-service
        url: /web/v3/api-docs