server:
  port: 8082
spring:
  cloud:
    gateway:
      routes:
        - id: web_route
          uri: http://localhost:8080
          predicates:
            - Path=/web/**
          filters:
            - RewritePath=/web/(?<remaining>.*), /${remaining}